version = 0.1

[default.global.parameters]
stack_name = "language-learning-api-dev"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
region = "us-west-2"
parameter_overrides = "Stage=dev"
stack_name = "language-learning-api-dev"
s3_prefix = "language-learning-api-dev"
disable_rollback = false
image_repositories = []

[default.validate.parameters]
lint = true
