version = 0.1

[default]
[default.global.parameters]
stack_name = "language-learning-api-prod"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "ap-east-1"
parameter_overrides = [
  "Stage=prod"
]
s3_prefix = "language-learning-api-prod"

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
