export const POPULAR_LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇬🇧', learners: '1.5B+' },
  { code: 'es', name: 'Spanish', flag: '🇪🇸', learners: '22M+' },
  { code: 'fr', name: 'French', flag: '🇫🇷', learners: '15M+' },
  { code: 'de', name: 'German', flag: '🇩🇪', learners: '12M+' },
  { code: 'it', name: 'Italian', flag: '🇮🇹', learners: '7M+' },
  { code: 'pt', name: 'Portuguese', flag: '🇵🇹', learners: '9M+' },
  { code: 'ru', name: 'Russian', flag: '🇷🇺', learners: '5M+' },
  { code: 'nl', name: 'Dutch', flag: '🇳🇱', learners: '2M+' },
  { code: 'sv', name: 'Swedish', flag: '🇸🇪', learners: '1M+' },
  { code: 'pl', name: 'Polish', flag: '🇵🇱', learners: '1M+' },
  { code: 'zh', name: 'Chinese', flag: '🇨🇳', learners: '18M+' },
  { code: 'ja', name: 'Japanese', flag: '🇯🇵', learners: '10M+' },
  { code: 'ko', name: 'Korean', flag: '🇰🇷', learners: '8M+' },
  { code: 'ar', name: 'Arabic', flag: '🇸🇦', learners: '6M+' },
  { code: 'hi', name: 'Hindi', flag: '🇮🇳', learners: '4M+' },
  { code: 'th', name: 'Thai', flag: '🇹🇭', learners: '2M+' },
  { code: 'vi', name: 'Vietnamese', flag: '🇻🇳', learners: '2M+' },
  { code: 'tr', name: 'Turkish', flag: '🇹🇷', learners: '3M+' },
  { code: 'el', name: 'Greek', flag: '🇬🇷', learners: '1M+' },
  { code: 'he', name: 'Hebrew', flag: '🇮🇱', learners: '1M+' },
];
